# Docs: <https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/customizing-dependency-updates>

version: 2
updates:
#   - package-ecosystem: npm
#     directory: /
#     schedule:
#       interval: weekly
#       day: "tuesday"
#       time: "01:00"
#       timezone: "Asia/Kolkata"
#     open-pull-requests-limit: 15

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: "tuesday"
      time: "01:00"
      timezone: "Asia/Kolkata"
    open-pull-requests-limit: 5
